# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
